version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: rinomed_postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: rinomed2026
      POSTGRES_USER: rinomed
      POSTGRES_PASSWORD: rinomed_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
